### ISSUE TITLE
issue funded does not appear in my profile

### ISSUE THREAD

**Issue by ninjasun** [gitcoinco/gitcoinco#45]
Scenario:
- I funded an issue
- I started to work on two issue

I can see the issue in the explorer but I can't see it in my profile where I can see the 2 issue I started.
If I try to self-assign the issue I funded all got messed up.
![issue_details_for_the_issue_created_notice_the_img_in_the_funder_card](https://user-images.githubusercontent.com/7422984/41508653-74a91e6a-7248-11e8-8d3c-1fd0498589b7.png)
![no_funded_issue_in_profile_page](https://user-images.githubusercontent.com/7422984/41508664-910ae8b8-7248-11e8-875c-751e4d34634f.png)

**Comment by thelostone-mc** [comment]
I'm not able to recreate this on local ! 
My steps: 
- navigate to a bounty
- start work (on rinkeyby network cause it's local)
- give start reason and submit
- visit the profile and it's there


<img width="1440" alt="screen shot 2018-06-18 at 10 30 09 am" src="https://user-images.githubusercontent.com/5358146/41518922-a3864ba0-72e2-11e8-9ea1-94747cf21c47.png">

Issue shows up on the profile: 

<img width="1440" alt="screen shot 2018-06-18 at 10 30 06 am" src="https://user-images.githubusercontent.com/5358146/41518921-a354208a-72e2-11e8-8fd9-aeb3ff55a8d5.png">


> If I try to self-assign the issue I funded all got messed up.

You can do that by changing the Metamask wallet address and you'll be able to start work on the issues created by you cause the true owner of the issue doesn't map to the github username but instead the wallet address with which the issue was bountied
