### ISSUE TITLE
Wrong payout behavior

### ISSUE THREAD

**Issue by hleb-albau** [gitcoinco/gitcoinco#52]
Hi, my flow was:
1. For issue https://github.com/cybercongress/cyber-search/issues/185 I created bounty.
2. @KevinLiLu completed issue.
3. To not  wait for Kevin submission, I selected advanced payout, filled fields with next values:
![image](https://user-images.githubusercontent.com/2991991/44661507-8b1f8780-aa13-11e8-82e0-c3d685b38270.png)
4. Gitcoin canceled issue, and send funds to unknown address **0xf0840Bba371D70581706bd15282Fb1AB08d1A6f4**. This address neither my, neither Kevin. See transactions https://etherscan.io/tx/0x102181ac3e797336e65d0debab61b4df95df43f8abebbb68f742c6bb0290b3aa
and https://etherscan.io/tx/0x4fbd36808827a48400f3e3033ae2ce4e8a5431f9724fdadecb7c910a67f1f635.

Expected behavior:
- Funds should be send to Kevin.

**Comment by owocki** [comment]
Hi @hleb-albau is this a new issue, or the one that i helped you with a week or two ago?  By the txid, it looks like its a new issue, right? 

Could you let me know what browser / version you are using?

> Gitcoin canceled issue, and send funds to unknown address 0xf0840Bba371D70581706bd15282Fb1AB08d1A6f4.

This is by design. For more information on how tips works, go to https://github.com/gitcoinco/web#of-a-tip

@KevinLiLu if you login to gitcoin and look for 'claim tip' in the nav, you can claim your funds from the ephemeral address there!

**Comment by KevinLiLu** [comment]
@hleb-albau I just claimed the tip and the transaction is pending https://etherscan.io/tx/0xd5217d43b2b38bdf2d1fac76969bd369361e35284eca1112ebf78a3cf7eb5346.

I will send the tip back to you so we can accept and complete the bounty for a better history. Which address should I send the funds to?

**Comment by hleb-albau** [comment]
@KevinLiLu **0x00725D89a2A2FB3B21Fd1035B579cbCDE4a0991b**.
@owocki Thanks for explanation. Also, such behavior not oblivious from advanced payout page ;( May be add some tip on the page?

**Comment by KevinLiLu** [comment]
@hleb-albau  Sent https://etherscan.io/tx/0xad018bd45692c2e9a112f1cb6c492ff8c5d8a86b8aeee08dd10e9131cf593402
